version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.win.iis
      args:
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - '80:80'
    depends_on:
      - ws
    restart: unless-stopped

  ws:
    build:
      context: .
      dockerfile: docker/ws/Dockerfile.win.node
    environment:
      PORT: ${WS_PORT:-3001}
    ports:
      - '3001:3001'
    restart: unless-stopped
